theme: 
  - osuny
  - osuny-plugin-centered-header
  - osuny-plugin-centered-footer
_merge: deep
params:
  summary:
    position: hero
  breadcrumb:
    position: after-hero
  search:
    active: true
  logo:
    header: '/assets/images/logo-blanc.svg'
    footer: '/assets/images/logo-french-craft.svg'
  home:
    head:
      title: site
  events:
    index:
      per_page: 36
  share_links:
    enabled: true
    email: true
    facebook: false
    linkedin: true
    mastodon: false
    telegram: false
    twitter: false
    whatsapp: false